<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Dell" name="com.test.DashBoardTestcases" tests="12" failures="1" timestamp="03 May 2019 08:21:08 GMT" time="560.144" errors="0">
  <testcase name="ChkAllSubModules_Dashboard" time="56.941" classname="com.test.DashBoardTestcases"/>
  <testcase name="Filter_RatingDistributionByAsset" time="50.529" classname="com.test.DashBoardTestcases"/>
  <testcase name="History_RatingDistributionByAsset" time="11.311" classname="com.test.DashBoardTestcases"/>
  <testcase name="Export_RatingDistributionByAsset" time="61.746" classname="com.test.DashBoardTestcases"/>
  <testcase name="Export_RiskRatingTrends" time="59.546" classname="com.test.DashBoardTestcases"/>
  <testcase name="Export_RiskRatingAverages" time="62.463" classname="com.test.DashBoardTestcases"/>
  <testcase name="Filter_TopEntities" time="64.759" classname="com.test.DashBoardTestcases"/>
  <testcase name="Export_TopEntities" time="23.077" classname="com.test.DashBoardTestcases"/>
  <testcase name="Filter_TopVulnerabilities" time="53.064" classname="com.test.DashBoardTestcases"/>
  <testcase name="Export_TopVulnerabilities" time="11.955" classname="com.test.DashBoardTestcases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.test.WrapperClass.assertTextXpath(WrapperClass.java:1293)
	at com.test.DashBoardTestcases.Export_TopVulnerabilities(DashBoardTestcases.java:595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Export_TopVulnerabilities -->
  <testcase name="Filter_TopAssets" time="53.286" classname="com.test.DashBoardTestcases"/>
  <testcase name="Export_TopAssets" time="51.467" classname="com.test.DashBoardTestcases"/>
</testsuite> <!-- com.test.DashBoardTestcases -->
